on_worker_boot do
  # Valid on Rails 4.1+ using the `config/database.yml` method of setting `pool` size
  ActiveRecord::Base.establish_connection
end

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

#production:
#  <<: *default
#  database: db/production.sqlite3
#
#development:
#  adapter: postgresql
#  encoding: utf8
#  database: project_development
#  pool: 5
#  username:
#  password:
#
#test: &TEST
#  adapter: postgresql
#  encoding: utf8
#  database: project_test
#  pool: 5
#  username:
#  password:
#
#production:
#  adapter: postgresql
#  encoding: utf8
#  database: project_production
#  pool: 5
#  username:
#  password:
#
#cucumber:
#  <<: *TEST